CREATE DATABASE IF NOT EXISTS DBProjeto1;

USE DBPROJETO1;

CREATE TABLE LOGIN
(
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	TIPO_USUARIO INT NOT NULL,
	CONSTRAINT PK_LOGIN PRIMARY KEY (LOGIN)
);

CREATE TABLE PERFIL
(
	COD_PER INT NOT NULL AUTO_INCREMENT,
	NOM_PER CHAR(7) NOT NULL,
	CONSTRAINT PK_COD_PERFIL PRIMARY KEY(COD_PER)
);

CREATE TABLE TRATAMENTO
(
	COD_TRA INT NOT NULL AUTO_INCREMENT,
	NOM_TRA CHAR(5) NOT NULL,
	CONSTRAINT PK_COD_TRATAMENTO PRIMARY KEY(COD_TRA)
);

CREATE TABLE PASSAGEIRO
(
	COD_PASSAGEIRO INT NOT NULL AUTO_INCREMENT,
	NOM_PAS CHAR(45) NOT NULL,
	SOBRENOME_PAS CHAR(45) NOT NULL,
	CEL_PAS CHAR(18) NOT NULL,
	DATA_NASC_PAS DATE NOT NULL,
	EMAIL_PAS CHAR(45),
	COD_TRA_PAS INT NOT NULL,
	COD_PER_PAS INT NOT NULL,
	CONSTRAINT PK_COD_PASSAGEIRO PRIMARY KEY(COD_PASSAGEIRO),
	CONSTRAINT FK_COD_TRA_PAS FOREIGN KEY(COD_TRA_PAS)
		REFERENCES TRATAMENTO(COD_TRA),
	CONSTRAINT FK_COD_PER_PAS FOREIGN KEY(COD_PER_PAS)
		REFERENCES PERFIL(COD_PER)
);

CREATE TABLE LOCALIDADE
(
	COD_LOC INT NOT NULL AUTO_INCREMENT,
	NOME_LOC CHAR(60) NOT NULL,
	CID_LOCA CHAR(60),
	CONSTRAINT PK_LOCALIDADE PRIMARY KEY(COD_LOC)
);

CREATE TABLE SITUACAO
(
	COD_SIT INT NOT NULL AUTO_INCREMENT,
	NOME_SIT CHAR(45) NOT NULL,
	CONSTRAINT PK_SITUACAO PRIMARY KEY(COD_SIT)
);

CREATE TABLE AERONAVE
(
	COD_AERO INT NOT NULL AUTO_INCREMENT,
	TIPO_AERO CHAR(12) NOT NULL,
	NOME_AERO VARCHAR(45) NOT NULL,
	QTD_ASSENTOS_AERO INT NOT NULL,
	CONSTRAINT PK_AERONAVE PRIMARY KEY(COD_AERO)
);

CREATE TABLE VOO
(
	COD_VOO INT NOT NULL AUTO_INCREMENT,
	VALOR_VOO DECIMAL(6,2) NOT NULL,
	COD_AERO_VOO INT NOT NULL,
	COD_SIT_VOO INT NOT NULL,
	CONSTRAINT PK_VOO PRIMARY KEY(COD_VOO),
	CONSTRAINT FK_AERONAVE_VOO FOREIGN KEY(COD_AERO_VOO)
		REFERENCES AERONAVE(COD_AERO),
	CONSTRAINT FK_SITUACAO_VOO FOREIGN KEY(COD_SIT_VOO)
		REFERENCES SITUACAO(COD_SIT)
);

CREATE TABLE LOCALIDADE_VOO
(
	COD_VOO INT NOT NULL,
	COD_LOC INT NOT NULL,
	TIPO CHAR(1) NOT NULL,
	DATA datetime,
	CONSTRAINT PK_LOCA_VOO PRIMARY KEY(COD_VOO, COD_LOC, TIPO, DATA),
	CONSTRAINT FK_LOCA_VOO_VOO FOREIGN KEY(COD_VOO)
		REFERENCES VOO(COD_VOO),
	CONSTRAINT FK_LOCA_VOO_LOCA FOREIGN KEY(COD_LOC)
		REFERENCES LOCALIDADE(COD_LOC)
);

CREATE TABLE PAGAMENTO
(
	COD_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
	NOM_TIT CHAR(90) NOT NULL,
	CPF_PAG CHAR(14) NOT NULL,
	DATA_PAG DATETIME NOT NULL,
	FORM_PAG CHAR(18) NOT NULL DEFAULT 'CARTÃO',
	CONSTRAINT PK_PAGAMENTO PRIMARY KEY(COD_PAGAMENTO)
);

CREATE TABLE CHEQUE
(
	COD_CHE INT NOT NULL AUTO_INCREMENT,
	BANC_CHE CHAR(40) NOT NULL,
	AGEN_CHE CHAR(6) NOT NULL,
	CONT_CHE CHAR(8) NOT NULL,
	COD_PAGAMENTO_CHE INT NOT NULL,
	CONSTRAINT PK_CHEQUE PRIMARY KEY(COD_CHE),
	CONSTRAINT FK_PAGAMENTO_CHEQUE FOREIGN KEY(COD_PAGAMENTO_CHE)
		REFERENCES PAGAMENTO(COD_PAGAMENTO)
);

CREATE TABLE PASSAGEM
(
	NUM_PASS INT NOT NULL AUTO_INCREMENT,
	PASS_IDA_VOLTA BINARY NOT NULL DEFAULT 1,
	PASS_CHECKIN DATETIME NOT NULL DEFAULT NOW(),
	NUM_ASSENTO_PASS INT,
	COD_PASSAGEIRO_PASS INT NOT NULL,
	COD_VOO_PASS INT NOT NULL,
	CONSTRAINT PK_PASSAGEM PRIMARY KEY(NUM_PASS),
	CONSTRAINT FK_PASSAGEM_PASSAGEIRO FOREIGN KEY(COD_PASSAGEIRO_PASS)
		REFERENCES PASSAGEIRO(COD_PASSAGEIRO),
	CONSTRAINT FK_PASSAGEM_VOO FOREIGN KEY(COD_VOO_PASS)
		REFERENCES VOO(COD_VOO)
);

CREATE TABLE RESERVA
(
	COD_RESERVA INT NOT NULL AUTO_INCREMENT,
	COD_AGEN_EXT CHAR(45) NOT NULL,
	STAT_RESERVA CHAR(8),
	NUM_PASS_RESERVA INT NOT NULL,
	CONSTRAINT PK_RESERVA PRIMARY KEY(COD_RESERVA),
	CONSTRAINT PK_RESERVA_PASSAGEM FOREIGN KEY(NUM_PASS_RESERVA)
		REFERENCES PASSAGEM(NUM_PASS)
);

CREATE TABLE PASSAGEMCOMPRA
(
	COD_PASSCOMP INT NOT NULL AUTO_INCREMENT,
	VAL_PASSCOMP DECIMAL(6,2) NOT NULL,
	PERC_TAXA_EMBARQUE DECIMAL(4,2) NOT NULL,
	DATA_COMP_PASSCOMP DATETIME NOT NULL,
	NUM_PASS_PASSCOMP INT NOT NULL,
	COD_PAGAMENTO_PASSCOMP INT NOT NULL,
	CONSTRAINT PK_PASSAGEMCOMPRA PRIMARY KEY(COD_PASSCOMP),
	CONSTRAINT FK_PASSAGEM_PASSAGEMCOMPRA FOREIGN KEY(NUM_PASS_PASSCOMP)
		REFERENCES PASSAGEM(NUM_PASS),
	CONSTRAINT FK_PAGAMENTO_PASSAGEMCOMPRA FOREIGN KEY(COD_PAGAMENTO_PASSCOMP)
		REFERENCES PAGAMENTO(COD_PAGAMENTO)
);

CREATE TABLE REEMBOLSO
(
	COD_REEM INT NOT NULL AUTO_INCREMENT,
	NOM_REEM CHAR(45) NOT NULL,
	BANC_REEM CHAR(40) NOT NULL,
	AGEN_REEM CHAR(6) NOT NULL,
	CONT_REEM CHAR(8) NOT NULL,
	CPF_TIT_REEM CHAR(14) NOT NULL,
	COD_PASSCOMP_REEMBOLSO INT NOT NULL,
	CONSTRAINT PK_REEMBOLSO PRIMARY KEY(COD_REEM),
	CONSTRAINT FK_PASSAGEMCOMPRA_REEMBOLSO FOREIGN KEY(COD_PASSCOMP_REEMBOLSO)
		REFERENCES PASSAGEMCOMPRA(COD_PASSCOMP)
);

CREATE TABLE ASSENTO
(
	COD_ASS INT NOT NULL AUTO_INCREMENT,
	ASSENTO_NUM_PASS INT NOT NULL,
	ASSENTO_COD_VOO INT NOT NULL,
	ASSENTO_COD_AERO INT NOT NULL,
	ASS_DISP TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT PK_ASSENTO PRIMARY KEY(COD_ASS,ASSENTO_NUM_PASS,ASSENTO_COD_VOO,ASSENTO_COD_AERO),
	CONSTRAINT FK_PASSAGEM_ASSENTO FOREIGN KEY(ASSENTO_NUM_PASS)
		REFERENCES PASSAGEM(NUM_PASS),
	CONSTRAINT FK_VOO_ASSENTO FOREIGN KEY(ASSENTO_COD_VOO)
		REFERENCES VOO(COD_VOO),
	CONSTRAINT FK_AERONAVE_ASSENTO FOREIGN KEY(ASSENTO_COD_AERO)
		REFERENCES AERONAVE(COD_AERO),
	CONSTRAINT CK_ASSENTO_ASS_DISP CHECK(ASS_DISP = 0 OR ASS_DISP = 1)
);